# Generated by Django 2.1 on 2018-09-08 09:13

from os import path, listdir
from django.db import migrations
from django.core.management import call_command

fixture_dir = path.abspath(
    path.join(path.dirname(__file__), '../fixtures/'))
fixture_surahs = 'surah_list.json'
fixture_ayahs = 'ayah_list.json'
fixture_reciters = 'reciters_list.json'

recitation_dir = path.join(fixture_dir, 'recitation')

#  get all recitations json files from fixtures/recitation directory
fixture_recitations_list = [
    path.join(recitation_dir, filename)
    for filename in listdir(recitation_dir)]


def load_surahs(apps, schema_editor):
    fixture_file = path.join(fixture_dir, fixture_surahs)
    call_command('loaddata', fixture_file)


def unload_surahs(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    Surah = apps.get_model("quran", "Surah")
    Surah.objects.all().delete()


def load_ayahs(apps, schema_editor):
    fixture_file = path.join(fixture_dir, fixture_ayahs)
    call_command('loaddata', fixture_file)


def unload_ayahs(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    Ayah = apps.get_model("quran", "Ayah")
    Ayah.objects.all().delete()


def load_reciters(apps, schema_editor):
    fixture_file = path.join(fixture_dir, fixture_reciters)
    call_command('loaddata', fixture_file)


def unload_reciters(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    Reciter = apps.get_model("quran", "Reciter")
    Reciter.objects.all().delete()


def load_recitations(apps, schema_editor):
    for fixture_file in fixture_recitations_list:
        call_command('loaddata', fixture_file)


def unload_recitations(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    Recitation = apps.get_model("quran", "Recitation")
    Recitation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_surahs, reverse_code=unload_surahs),
        migrations.RunPython(load_ayahs, reverse_code=unload_ayahs),
        migrations.RunPython(load_reciters, reverse_code=unload_reciters),
        migrations.RunPython(
            load_recitations, reverse_code=unload_recitations),
    ]
