# Generated by Django 2.1 on 2018-09-08 09:13

from os import path
from django.db import migrations
from django.core.management import call_command

fixture_dir = path.abspath(
    path.join(path.dirname(__file__), '../../fixtures'))
fixture_filename = 'surah_fixture.json'


def load_fixture(apps, schema_editor):
    fixture_file = path.join(fixture_dir, fixture_filename)
    call_command('loaddata', fixture_file)


def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    Surah = apps.get_model("surah", "Surah")
    Surah.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('surah', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
