# Generated by Django 2.1 on 2018-09-09 17:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_auto_20180908_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('ayah_id', models.AutoField(
                    primary_key=True,
                    serialize=False)),
                ('ayah_text', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(
                        blank=True,
                        default='',
                        max_length=255),
                    default=list,
                    size=None)),
                ('surah_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='ayahs',
                    to='quran.Surah')),
            ],
        ),
    ]
