# Generated by Django 2.1 on 2018-09-12 17:38

from os import path
from django.db import migrations
from django.core.management import call_command


fixture_dir = path.abspath(
    path.join(path.dirname(__file__), '../fixtures/'))
fixture_filename = 'ayahs_list.json'


def load_ayahs(apps, schema_editor):
    fixture_file = path.join(fixture_dir, fixture_filename)
    call_command('loaddata', fixture_file)


def unload_ayahs(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    Ayah = apps.get_model("quran", "Ayah")
    Ayah.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0003_ayah'),
    ]

    operations = [
        migrations.RunPython(load_ayahs, reverse_code=unload_ayahs),
    ]
